### PR TITLE
Fix browser bundle generation

### PR DESCRIPTION
**Pull request by rmg**
Switch from minifyify to uglifyify, update browserify, and add exorcist. The end result is a more resilient bundling script that has properly externalized sourcemaps.

This _should_ resolve:
 - #53 
 - strongloop/strongloop#337
 - request/request#2585

Manual testing locally:
 - `cd ../strongloop`
 - `npm install && npm link ../strong-mesh-client`
 - `slc pm &`
 - `slc arc`
 - app start/stop
 - deploy
 - "remote" app start/stop
 - tracing

I didn't do an exhaustive test-all-the-features run through, but enough that I'm confident that the new bundle generated by these changes works at least as well as the bundles that were being generated before the breakage introduced by request v2.80.0 (request/request#2585).

@svennam92 @ritch @sam-github @kraman PTAL. The intention is to release v1.6.5 as soon as this merges.

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by sam-github** [comment]
LGTM at source code change level, but I don't know anything about browserification, @kraman @ritch , any idea how to verify? "Just use Arc", maybe?

**Comment by kraman** [comment]
LGTM as well and yes just have to spin up arc and use it to start/stop PM.

**Comment by rmg** [comment]
@sam-github @kraman maybe I wasn't clear. What I listed was how I _did_ test this locally.

Unfortunately it seems that there's something about npm v2 that is still managing to trigger the original issue.

**Comment by rmg** [comment]
@sam-github @kraman it looks like omitting `ajv` from the bundle is another way of resolving this and it can be done without making any _other_ changes. Thoughts on which way to go?

**Comment by svennam92** [comment]
LGTM as well, but prefer the simpler alternative. less changes means less chance at breakage :)

**Comment by rmg** [comment]
Works for me. Closing in favour of #58.

**Pull request closed without merging**
