### PR TITLE
Updating mesh-models to get capabilities api

### PR DESCRIPTION
**Pull request by kraman**
Connect to strongloop-internal/scrum-nodeops#454

### CODE REVIEW

**Comment by ritch** [comment]
A couple of the jobs are failing... not sure why. This should be released as a major version so that it isn't accidentally introduced into older versions of arc.

**Comment by ritch** [comment]
Otherwise LGTM

**Comment by kraman** [comment]
@ritch major version updated

**Comment by kraman** [comment]
@slnode test please

**Pull request merged**
