### PR TITLE
fix expression order for connection error check

### PR DESCRIPTION
**Pull request by ritch**
/to @kraman 
/cc @Setogit 

Closes https://github.com/strongloop-internal/scrum-nodeops/issues/434

### CODE REVIEW

**Comment by kraman** [comment]
duplicate of @Setogit 's issue?

**Comment by sam-github** [comment]
@ritch: @Setogit's issue: https://github.com/strongloop-internal/scrum-nodeops/issues/434

**Comment by ritch** [comment]
@kraman @sam-github ??? this is a PR that fixes that issue.

**Comment by ritch** [comment]
ah I didn't see his PR... merged his

**Pull request closed without merging**
