### PR TITLE
Update mesh-client with express metrics changes

### PR DESCRIPTION
**Pull request by kraman**
Connect to strongloop/strong-arc#1188

### CODE REVIEW

**Comment by ritch** [comment]
@kraman LGTM

**Comment by rmg** [comment]
@slnode test please

**Comment by sam-github** [comment]
/to @rmg I think this should have updated the package.json dep on strong-mesh-models to `^6.0.0`, as-is, I don't think it will get the changes from https://github.com/strongloop/strong-mesh-models/pull/41

**Comment by rmg** [comment]
I've resolved the version mismatch by branching strong-mesh-models for 5.x and cherry-picking strongloop/strong-mesh-models#41 on to it.

**Pull request merged**
