### PR TITLE
Remove runtime client bundle generation

### PR DESCRIPTION
**Pull request by kraman**

### CODE REVIEW

**Comment by rmg** [comment]
The browser bundle is generated at install time, so browserify must be a regular dependency. I changed this because otherwise we need to generate the bundle at publish time and release a new version every time we make a strong-mesh-models release so that the bundled version is updated. It also makes `npm pack` highly dependent on which registry is selected at the moment.

**Comment by kraman** [comment]
@rmg hm thats unfortunate. then this PR is not needed since the original intent was to move browserify and minifyify to dev deps

**Comment by ritch** [comment]
Thanks @rmg

**Comment by raymondfeng** [comment]
@rmg The `browserify` dependency of `strong-mesh-client` is failing `npm install -g strongloop`. It's a CRITICAL issue to fix. You can simply reproduce it by running `cd /tmp; npm i strong-mesh-client`

**Pull request closed without merging**
